# For more info on HTTP files go to https://aka.ms/vs/httpfile

@SmartXApi_HostAddress = https://localhost:7031

### Float telemetry
POST {{SmartXApi_HostAddress}}/api/telemetry/float
Content-Type: application/json

{
"deviceId": "ESP32-0001",
"metric": "Temperature",
"value": 29.4,
"unit": "°C"
}

### Integer telemetry
POST {{SmartXApi_HostAddress}}/api/telemetry/int
Content-Type: application/json

{
"deviceId": "ESP32-0002",
"metric": "PowerWattage",
"value": 2100,
"unit": "W"
}

### Boolean telemetry
POST {{SmartXApi_HostAddress}}/api/telemetry/bool
Content-Type: application/json

{
"deviceId": "ESP32-0003",
"metric": "ValveState",
"value": false,
"unit": "State"
}



### Register a new Smart-X device
POST {{SmartXApi_HostAddress}}/api/devices/register
Content-Type: application/json

{
"deviceId": "ESP32-0005",
"macAddress": "AA:BB:CC:11:22:05",
"deploymentLocation": "Facility B / Zone 2 / Node 1",
"category": 0
}


### Upload hardware log
POST {{SmartXApi_HostAddress}}/api/devices/ESP32-0001/attachments
Content-Type: multipart/form-data; boundary=SmartXBoundary

--SmartXBoundary
Content-Disposition: form-data; name="attachmentCategory"

HardwareLog
--SmartXBoundary
Content-Disposition: form-data; name="file"; filename="hardware-log.txt"
Content-Type: text/plain

< ./hardware-log.txt
--SmartXBoundary--

### Normal temperature telemetry test
POST https://localhost:7031/api/telemetry/float
Content-Type: application/json

{
"deviceId": "ESP32-0001",
"metric": "Temperature",
"value": 25.5,
"unit": "C"
}

### Abnormal temperature spike test

POST https://localhost:7031/api/telemetry/float
Content-Type: application/json

{
"deviceId": "ESP32-0001",
"metric": "Temperature",
"value": 58.7,
"unit": "C"
}


### Abnormal power consumption test

POST https://localhost:7031/api/telemetry/int
Content-Type: application/json

{
"deviceId": "ESP32-0002",
"metric": "PowerWattage",
"value": 7200,
"unit": "W"
}


### View detected anomalies

GET https://localhost:7031/api/anomalies



### Dashboard anomaly test - temperature

POST https://localhost:7031/api/telemetry/float
Content-Type: application/json

{
"deviceId": "ESP32-0001",
"metric": "Temperature",
"value": 58.7,
"unit": "C"
}


### Dashboard anomaly test - wattage

POST https://localhost:7031/api/telemetry/int
Content-Type: application/json

{
"deviceId": "ESP32-0002",
"metric": "PowerWattage",
"value": 7200,
"unit": "W"
}




### View device attachments

GET https://localhost:7031/api/devices/ESP32-0001/attachments














